# Generated by Django 4.2 on 2023-06-19 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stackapp', '0003_alter_ticket_options_ticket_code_ticket_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.TextField(default='None'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('solution', models.TextField(max_length=500)),
                ('code', models.TextField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('solution_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stackapp.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
    ]
