# Generated by Django 4.2 on 2023-06-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackapp', '0004_alter_ticket_code_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='code',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
