# Generated by Django 4.2 on 2023-06-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackapp', '0006_alter_ticket_created_date_alter_ticket_maker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
