# Generated by Django 4.2 on 2023-10-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackapp', '0008_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_email_activated',
            field=models.BooleanField(default=False),
        ),
    ]
