# Generated by Django 4.2 on 2023-11-10 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('programing_language', models.CharField(max_length=20)),
                ('course_name', models.CharField(blank=True, max_length=50)),
                ('describe', models.TextField(max_length=750)),
                ('code', models.TextField(max_length=500)),
                ('screenshot', models.ImageField(blank=True, upload_to='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('github', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
    ]
